---
# Secret for PostgreSQL credentials
#
# This secret contains the PostgreSQL credentials and S3 access keys
# required for the backup process. The credentials are stored in a Base64
# encoded format to ensure security. It is recommended to not store
# sensitive information in Git repositories. Instead, use a secret management
# solution or a secure vault to manage sensitive data.
#
apiVersion: v1
kind: Secret
metadata:
  name: n8n-postgres-backup-secrets
  namespace: myai01
type: Opaque
data:
  #!! RECOMMENDED: do not save values in Git
  # Base64 encoded values - replace with your actual credentials
  POSTGRES_PASSWORD: <base64-encoded-password>
  POSTGRES_USER: <base64-encoded-username> # https://docs.n8n.io/hosting/configuration/supported-databases-settings/#postgresdb
  S3_ACCESS_KEY: <base64-encoded-access-key>
  S3_SECRET_KEY: <base64-encoded-secret-key>
...