---
# Secret for PostgreSQL credentials
#
# This secret contains the PostgreSQL credentials and S3 access keys
# required for the backup process. The credentials are stored in a Base64
# encoded format to ensure security. It is recommended to not store
# sensitive information in Git repositories. Instead, use a secret management
# solution or a secure vault to manage sensitive data.
#
apiVersion: v1
kind: Secret
metadata:
  name: postgres-backup-secrets
  namespace: myai01
type: Opaque
data:
  ##!! RECOMMENDED: do not save values in Git
  ## This is a sample secret to provide the key names and structure.
  ## Values need to be Base64 encoded - replace with your actual credentials
  POSTGRES_PASSWORD: <base64-encoded-password>
  POSTGRES_USER: <base64-encoded-username>
  S3_ACCESS_KEY: <base64-encoded-access-key>
  S3_SECRET_KEY: <base64-encoded-secret-key>
...
